/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'revisionInterval' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'importance' : IDL.Text,
  'advancedPracticeCompleted' : IDL.Bool,
  'lastStudied' : IDL.Opt(Time),
  'studyHours' : IDL.Nat,
  'pyqsCompleted' : IDL.Bool,
  'theoryCompleted' : IDL.Bool,
  'isComplete' : IDL.Bool,
});
export const TimeSlot = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'activityType' : IDL.Text,
  'endTime' : Time,
  'description' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const PerformanceBlock = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'focusScore' : IDL.Nat,
  'blockId' : IDL.Nat,
  'productivity' : IDL.Nat,
});
export const ConsistencyDNA = IDL.Record({
  'lastEntryDate' : IDL.Opt(IDL.Text),
  'lastUpdate' : Time,
  'daysTracked' : IDL.Nat,
  'daysConsistent' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addChapter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Chapter],
      [],
    ),
  'addTimeSlot' : IDL.Func([Time, Time, IDL.Text, IDL.Text], [TimeSlot], []),
  'deleteTimeSlot' : IDL.Func([IDL.Nat], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getPerformanceBlocks' : IDL.Func([], [IDL.Vec(PerformanceBlock)], ['query']),
  'getSortedConsistencyLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ConsistencyDNA))],
      ['query'],
    ),
  'getTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getUserConsistency' : IDL.Func([], [ConsistencyDNA], ['query']),
  'getWarModeStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastSession' : IDL.Opt(Time),
          'totalStudyTime' : IDL.Nat,
          'completedPomodoros' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'recordPerformanceBlock' : IDL.Func(
      [Time, Time, IDL.Nat, IDL.Nat],
      [PerformanceBlock],
      [],
    ),
  'registerUser' : IDL.Func([], [], []),
  'toggleChapterCompletion' : IDL.Func([IDL.Nat], [Chapter], []),
  'toggleCompletion' : IDL.Func([IDL.Nat], [TimeSlot], []),
  'updateConsistency' : IDL.Func([IDL.Bool, IDL.Text], [ConsistencyDNA], []),
  'updateTimeSlot' : IDL.Func(
      [IDL.Nat, Time, Time, IDL.Text, IDL.Text],
      [TimeSlot],
      [],
    ),
  'updateWarModeStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'revisionInterval' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'importance' : IDL.Text,
    'advancedPracticeCompleted' : IDL.Bool,
    'lastStudied' : IDL.Opt(Time),
    'studyHours' : IDL.Nat,
    'pyqsCompleted' : IDL.Bool,
    'theoryCompleted' : IDL.Bool,
    'isComplete' : IDL.Bool,
  });
  const TimeSlot = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'activityType' : IDL.Text,
    'endTime' : Time,
    'description' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const PerformanceBlock = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'focusScore' : IDL.Nat,
    'blockId' : IDL.Nat,
    'productivity' : IDL.Nat,
  });
  const ConsistencyDNA = IDL.Record({
    'lastEntryDate' : IDL.Opt(IDL.Text),
    'lastUpdate' : Time,
    'daysTracked' : IDL.Nat,
    'daysConsistent' : IDL.Nat,
  });
  
  return IDL.Service({
    'addChapter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Chapter],
        [],
      ),
    'addTimeSlot' : IDL.Func([Time, Time, IDL.Text, IDL.Text], [TimeSlot], []),
    'deleteTimeSlot' : IDL.Func([IDL.Nat], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getPerformanceBlocks' : IDL.Func(
        [],
        [IDL.Vec(PerformanceBlock)],
        ['query'],
      ),
    'getSortedConsistencyLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ConsistencyDNA))],
        ['query'],
      ),
    'getTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getUserConsistency' : IDL.Func([], [ConsistencyDNA], ['query']),
    'getWarModeStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastSession' : IDL.Opt(Time),
            'totalStudyTime' : IDL.Nat,
            'completedPomodoros' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'recordPerformanceBlock' : IDL.Func(
        [Time, Time, IDL.Nat, IDL.Nat],
        [PerformanceBlock],
        [],
      ),
    'registerUser' : IDL.Func([], [], []),
    'toggleChapterCompletion' : IDL.Func([IDL.Nat], [Chapter], []),
    'toggleCompletion' : IDL.Func([IDL.Nat], [TimeSlot], []),
    'updateConsistency' : IDL.Func([IDL.Bool, IDL.Text], [ConsistencyDNA], []),
    'updateTimeSlot' : IDL.Func(
        [IDL.Nat, Time, Time, IDL.Text, IDL.Text],
        [TimeSlot],
        [],
      ),
    'updateWarModeStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };