/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'subject' : string,
  'revisionInterval' : bigint,
  'difficulty' : string,
  'name' : string,
  'importance' : string,
  'advancedPracticeCompleted' : boolean,
  'lastStudied' : [] | [Time],
  'studyHours' : bigint,
  'pyqsCompleted' : boolean,
  'theoryCompleted' : boolean,
  'isComplete' : boolean,
}
export interface ConsistencyDNA {
  'lastEntryDate' : [] | [string],
  'lastUpdate' : Time,
  'daysTracked' : bigint,
  'daysConsistent' : bigint,
}
export interface PerformanceBlock {
  'startTime' : Time,
  'endTime' : Time,
  'focusScore' : bigint,
  'blockId' : bigint,
  'productivity' : bigint,
}
export type Time = bigint;
export interface TimeSlot {
  'id' : bigint,
  'startTime' : Time,
  'activityType' : string,
  'endTime' : Time,
  'description' : string,
  'chapter' : string,
  'isComplete' : boolean,
}
export interface _SERVICE {
  'addChapter' : ActorMethod<[string, string, bigint, string, string], Chapter>,
  'addTimeSlot' : ActorMethod<[Time, Time, string, string, string], TimeSlot>,
  'deleteTimeSlot' : ActorMethod<[bigint], undefined>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getPerformanceBlocks' : ActorMethod<[], Array<PerformanceBlock>>,
  'getSortedConsistencyLeaderboard' : ActorMethod<
    [],
    Array<[Principal, ConsistencyDNA]>
  >,
  'getTimeSlots' : ActorMethod<[], Array<TimeSlot>>,
  'getUserConsistency' : ActorMethod<[], ConsistencyDNA>,
  'getWarModeStats' : ActorMethod<
    [],
    {
      'totalWarModeStudyTime' : bigint,
      'lastSession' : [] | [Time],
      'totalStudyTime' : bigint,
      'warModeOnlyStudyTime' : bigint,
      'completedPomodoros' : bigint,
    }
  >,
  'recordPerformanceBlock' : ActorMethod<
    [Time, Time, bigint, bigint],
    PerformanceBlock
  >,
  'registerUser' : ActorMethod<[], undefined>,
  'toggleChapterCompletion' : ActorMethod<[bigint], Chapter>,
  'toggleCompletion' : ActorMethod<[bigint], TimeSlot>,
  'updateChapterRevision' : ActorMethod<
    [bigint, boolean, boolean, boolean],
    undefined
  >,
  'updateConsistency' : ActorMethod<[boolean, string], ConsistencyDNA>,
  'updateTimeSlot' : ActorMethod<
    [bigint, Time, Time, string, string, string],
    TimeSlot
  >,
  'updateWarModeStats' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];