/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    id: bigint;
    startTime: Time;
    activityType: string;
    endTime: Time;
    description: string;
    chapter: string;
    isComplete: boolean;
}
export type Time = bigint;
export interface PerformanceBlock {
    startTime: Time;
    endTime: Time;
    focusScore: bigint;
    blockId: bigint;
    productivity: bigint;
}
export interface ConsistencyDNA {
    lastEntryDate?: string;
    lastUpdate: Time;
    daysTracked: bigint;
    daysConsistent: bigint;
}
export interface Chapter {
    id: bigint;
    subject: string;
    revisionInterval: bigint;
    difficulty: string;
    name: string;
    importance: string;
    advancedPracticeCompleted: boolean;
    lastStudied?: Time;
    studyHours: bigint;
    pyqsCompleted: boolean;
    theoryCompleted: boolean;
    isComplete: boolean;
}
export interface backendInterface {
    addChapter(name: string, subject: string, revisionInterval: bigint, difficulty: string, importance: string): Promise<Chapter>;
    addTimeSlot(startTime: Time, endTime: Time, activityType: string, description: string, chapter: string): Promise<TimeSlot>;
    deleteTimeSlot(id: bigint): Promise<void>;
    getAllChapters(): Promise<Array<Chapter>>;
    getPerformanceBlocks(): Promise<Array<PerformanceBlock>>;
    getSortedConsistencyLeaderboard(): Promise<Array<[Principal, ConsistencyDNA]>>;
    getTimeSlots(): Promise<Array<TimeSlot>>;
    getUserConsistency(): Promise<ConsistencyDNA>;
    getWarModeStats(): Promise<{
        totalWarModeStudyTime: bigint;
        lastSession?: Time;
        totalStudyTime: bigint;
        warModeOnlyStudyTime: bigint;
        completedPomodoros: bigint;
    }>;
    recordPerformanceBlock(startTime: Time, endTime: Time, focusScore: bigint, productivity: bigint): Promise<PerformanceBlock>;
    registerUser(): Promise<void>;
    toggleChapterCompletion(chapterId: bigint): Promise<Chapter>;
    toggleCompletion(id: bigint): Promise<TimeSlot>;
    updateChapterRevision(chapterId: bigint, theoryCompleted: boolean, pyqsCompleted: boolean, advancedPracticeCompleted: boolean): Promise<void>;
    updateConsistency(isConsistent: boolean, currentDate: string): Promise<ConsistencyDNA>;
    updateTimeSlot(id: bigint, startTime: Time, endTime: Time, activityType: string, description: string, chapter: string): Promise<TimeSlot>;
    updateWarModeStats(pomodoros: bigint, studyTime: bigint): Promise<void>;
}
import type { Chapter as _Chapter, ConsistencyDNA as _ConsistencyDNA, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addChapter(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<Chapter> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Chapter_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Chapter_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTimeSlot(arg0: Time, arg1: Time, arg2: string, arg3: string, arg4: string): Promise<TimeSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimeSlot(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimeSlot(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteTimeSlot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimeSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimeSlot(arg0);
            return result;
        }
    }
    async getAllChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChapters();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChapters();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceBlocks(): Promise<Array<PerformanceBlock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceBlocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceBlocks();
            return result;
        }
    }
    async getSortedConsistencyLeaderboard(): Promise<Array<[Principal, ConsistencyDNA]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedConsistencyLeaderboard();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedConsistencyLeaderboard();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimeSlots(): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlots();
            return result;
        }
    }
    async getUserConsistency(): Promise<ConsistencyDNA> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConsistency();
                return from_candid_ConsistencyDNA_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConsistency();
            return from_candid_ConsistencyDNA_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarModeStats(): Promise<{
        totalWarModeStudyTime: bigint;
        lastSession?: Time;
        totalStudyTime: bigint;
        warModeOnlyStudyTime: bigint;
        completedPomodoros: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarModeStats();
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarModeStats();
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPerformanceBlock(arg0: Time, arg1: Time, arg2: bigint, arg3: bigint): Promise<PerformanceBlock> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPerformanceBlock(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPerformanceBlock(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser();
            return result;
        }
    }
    async toggleChapterCompletion(arg0: bigint): Promise<Chapter> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChapterCompletion(arg0);
                return from_candid_Chapter_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChapterCompletion(arg0);
            return from_candid_Chapter_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCompletion(arg0: bigint): Promise<TimeSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCompletion(arg0);
            return result;
        }
    }
    async updateChapterRevision(arg0: bigint, arg1: boolean, arg2: boolean, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapterRevision(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapterRevision(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateConsistency(arg0: boolean, arg1: string): Promise<ConsistencyDNA> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConsistency(arg0, arg1);
                return from_candid_ConsistencyDNA_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConsistency(arg0, arg1);
            return from_candid_ConsistencyDNA_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTimeSlot(arg0: bigint, arg1: Time, arg2: Time, arg3: string, arg4: string, arg5: string): Promise<TimeSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimeSlot(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimeSlot(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateWarModeStats(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWarModeStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWarModeStats(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Chapter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chapter): Chapter {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ConsistencyDNA_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsistencyDNA): ConsistencyDNA {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalWarModeStudyTime: bigint;
    lastSession: [] | [_Time];
    totalStudyTime: bigint;
    warModeOnlyStudyTime: bigint;
    completedPomodoros: bigint;
}): {
    totalWarModeStudyTime: bigint;
    lastSession?: Time;
    totalStudyTime: bigint;
    warModeOnlyStudyTime: bigint;
    completedPomodoros: bigint;
} {
    return {
        totalWarModeStudyTime: value.totalWarModeStudyTime,
        lastSession: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastSession)),
        totalStudyTime: value.totalStudyTime,
        warModeOnlyStudyTime: value.warModeOnlyStudyTime,
        completedPomodoros: value.completedPomodoros
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: string;
    revisionInterval: bigint;
    difficulty: string;
    name: string;
    importance: string;
    advancedPracticeCompleted: boolean;
    lastStudied: [] | [_Time];
    studyHours: bigint;
    pyqsCompleted: boolean;
    theoryCompleted: boolean;
    isComplete: boolean;
}): {
    id: bigint;
    subject: string;
    revisionInterval: bigint;
    difficulty: string;
    name: string;
    importance: string;
    advancedPracticeCompleted: boolean;
    lastStudied?: Time;
    studyHours: bigint;
    pyqsCompleted: boolean;
    theoryCompleted: boolean;
    isComplete: boolean;
} {
    return {
        id: value.id,
        subject: value.subject,
        revisionInterval: value.revisionInterval,
        difficulty: value.difficulty,
        name: value.name,
        importance: value.importance,
        advancedPracticeCompleted: value.advancedPracticeCompleted,
        lastStudied: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastStudied)),
        studyHours: value.studyHours,
        pyqsCompleted: value.pyqsCompleted,
        theoryCompleted: value.theoryCompleted,
        isComplete: value.isComplete
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastEntryDate: [] | [string];
    lastUpdate: _Time;
    daysTracked: bigint;
    daysConsistent: bigint;
}): {
    lastEntryDate?: string;
    lastUpdate: Time;
    daysTracked: bigint;
    daysConsistent: bigint;
} {
    return {
        lastEntryDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.lastEntryDate)),
        lastUpdate: value.lastUpdate,
        daysTracked: value.daysTracked,
        daysConsistent: value.daysConsistent
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _ConsistencyDNA]): [Principal, ConsistencyDNA] {
    return [
        value[0],
        from_candid_ConsistencyDNA_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chapter>): Array<Chapter> {
    return value.map((x)=>from_candid_Chapter_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _ConsistencyDNA]>): Array<[Principal, ConsistencyDNA]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
